### ISSUE TITLE
Can't load sample projects after local installation

### ISSUE THREAD

**Issue by jperna7254** [NVIDIA/cuda-samples#207]
I followed the procedure for installation of the CUDA Toolkit found here
https://docs.nvidia.com/cuda/cuda-quick-start-guide/index.html#local-installer
After cloning this repo and attempting to load the projects I got the following error regarding importing the projects.
```
C:\Users\jerem\source\repos\cuda-samples\Samples\0_Introduction\clock_nvrtc\clock_nvrtc_vs2022.vcxproj : error  : The imported project "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 12.1.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 12.1.props" is correct, and that the file exists on disk.  C:\Users\jerem\source\repos\cuda-samples\Samples\0_Introduction\clock_nvrtc\clock_nvrtc_vs2022.vcxproj
```
This error popped up for all the projects and the reason was the `CUDA 12.1.props` and `CUDA 12.1.targets` files were not where my `VCTargetsPath` was pointing. My CUDA props file was located here
```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\extras\visual_studio_integration\MSBuildExtensions\CUDA 12.1.props
```
But the `VCTargetsPath` was pointing here
```
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations
```
So, it seems the default location for the local installation of the toolkit doesn't match where Visual Studio is expecting to find the visual c++ target files.

**Comment by eabase** [comment]
This sucks, what's the solution?
I'm not gonna downgrade, these nvidia/MS dudes just gotta get their shit together.

**Comment by iamparik** [comment]
@jperna7254 @eabase in case you didn't find the fix, here is how I fixed the issue to run the samples. 

In my case the error was "The imported project "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 12.4.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\\BuildCustomizations\CUDA 12.4.props" is correct, and that the file exists on disk." 

**Step 1**. I checked my .props and .targets version on my system, and I had 12.3 and 12.5 only. (so check what you have on your system, image below for location and files as on my system)

![image](https://github.com/NVIDIA/cuda-samples/assets/145947291/5ea4a281-a8f4-42ba-9dab-3ecc011df63e)

**Step 2.** Now go to your local repository with cuda samples and edit the .vcxproj file associated with your visual studio version. In my case this is *vs2022.vcxproj. We edit this, since .vcxproj is loosely the makefile equivalent for windows visual studio. Now change .props and .targets versions in the .vcxproj file to be the same as the ones in step 1 above.  In my case I changed 12.4 to 12.5, which was the latest I had (see image below). 

![image](https://github.com/NVIDIA/cuda-samples/assets/145947291/88bc8de2-80de-4ac6-8952-fb7f8108372a)

**Comment by Anonymous-Humanoid** [comment]
Almost 2 years and this issue still persists. Found the CUDA 12.8 .props and .targets under `%PROGRAMFILES%\NVIDIA GPU Computing Toolkit\CUDA\v12.8\extras\visual_studio_integration\MSBuildExtensions`. Had to follow the above steps and modify the `CUDAPropsPath` element to point to the aforementioned directory instead of `$(VCTargetsPath)\BuildCustomizations`.
